# Generated by Django 3.2 on 2021-04-20 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='creation_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='message_content',
            new_name='message',
        ),
    ]
